### ISSUE TITLE
NPM Start Renders error

### ISSUE THREAD

**Issue by Blackbaud-MichaelCollier** [blackbaud/sky-api-tutorial-implicit-flow-angular2#10]
npm ERR! Darwin 17.7.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! skyux2-starter@0.0.1 start: `webpack-dev-server --config config/webpack.dev.js --progress --profile --watch`
npm ERR! Exit status 1
 Failed at the skyux2-starter@0.0.1 start script 'webpack-dev-server --config config/webpack.dev.js --progress --profile --watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.

**Comment by Blackbaud-MichaelCollier** [comment]
We are going to try using angular CLI to address this issue.  The exact date to fix is TBD.

**Comment by Blackbaud-BobbyEarl** [comment]
I would be really surprised if this code sample is able to be ran at all given the dated dependencies.

I'm going to close due to inactivity, but have another task to evaluate all our code samples and make sure they're:

- Adding value
- Up-to-date
